# Klasifikasi Jenis Kelamin Berdasarkan Nama Menggunakan Machine Learning

                          Vicky Vernando Dasta - Hafizan Anas Sidiqi   
                                            2017
---


## Abstrak:

> sebuah penelitian terhadap nama-nama orang yang sering dipakai di Indonesia dengan tujuan membuat mesin yang bisa membedakan jenis kelamin dari nama tersebut**

          

---


## Latar Belakang

- sering terjadi kesalahan interpretasi gender dari nama seseorang
- diperlukannya mesin yang bisa melihat pola dan hubungan antara corpus dari nama dengan gendernya

## Teori

*nama* dalam Kamus Besar Bahasa Indonesia berarti *kata untuk menyebut atau memanggil orang (tempat, barang, binatang, dan sebagainya)*. 


## Metodologi



## Hasil 

## Kesimpulan
**MESIN BISA MEMBEDAKAN JENIS KELAMIN DARI SEBUAH NAMA**





In [73]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [74]:
count_vectorizer = CountVectorizer()
tfid_vectorizer = TfidfVectorizer()
label_encoder = preprocessing.LabelEncoder()

In [75]:
import warnings
warnings.simplefilter("ignore")

In [66]:
df = pd.read_csv('data/cleaned-data.csv')
print("sebelum")
print(df.head())
print()
lower_me = lambda name: name.lower() 

df["NAMA"] = df["NAMA"].apply(lower_me)
df["Jenis Kelamin"] = df["Jenis Kelamin"].apply(lower_me)

print()
print("sesudah")
print(df.head())


sebelum
                   NAMA Jenis Kelamin
0  ADITYA KUSUMANINGRUM     Perempuan
1         ADNAN AGUNG P     Laki-laki
2        AGNES MORIWOTI     Perempuan
3    ANDINI NURAHMAYANI     Perempuan
4             APHARUDIN     Laki-laki


sesudah
                   NAMA Jenis Kelamin
0  aditya kusumaningrum     perempuan
1         adnan agung p     laki-laki
2        agnes moriwoti     perempuan
3    andini nurahmayani     perempuan
4             apharudin     laki-laki


In [67]:
labels = label_encoder.fit_transform(df["Jenis Kelamin"])
labels = labels.reshape(labels.shape[0], 1)
data = tfid_vectorizer.fit_transform(df["NAMA"])

In [83]:
x_train, x_test, y_train, y_test = train_test_split(data, labels)

In [69]:
print(x_train.shape, y_train.shape)

(438, 1047) (438, 1)


In [70]:
model = LogisticRegression()
model.fit(x_train, y_train)
print(model.score(x_test, y_test))

predicted = model.predict(x_test)
print(confusion_matrix(y_test, predicted))

0.6598639455782312
[[ 0  0  1]
 [ 0 17 44]
 [ 0  5 80]]


In [71]:
model = SVC()
model.fit(x_train, y_train)
print(model.score(x_test, y_test))

predicted = model.predict(x_test)
print(confusion_matrix(y_test, predicted))

0.5782312925170068
[[ 0  0  1]
 [ 0  0 61]
 [ 0  0 85]]


In [80]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(max_iter=100000)
model.fit(x_train, y_train)
print(model.score(x_test, y_test))

predicted = model.predict(x_test)
print(confusion_matrix(y_test, predicted))

0.6462585034013606
[[ 0  1  0]
 [ 0 56  5]
 [ 0 46 39]]


In [77]:
model

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)